@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTY1MjI2Nzd9.CZuItkKq8_K6K38g5yaMeBucYCgWpq1CARGX4_AqIms

### INDEX action

GET http://localhost:3000/students.json


### SHOW action

GET http://localhost:3000/students/1.json


### CREATE action

POST http://localhost:3000/students.json
Authorization: Bearer {{jwt}}
# Content-Type: application/json

{
  "first_name": "This",
  "last_name": "Is",
  "email": "A",
  "phone_number": "Test"
}

### UPDATE action

PATCH http://localhost:3000/students/1.json
Content-Type: application/json

{
  
}

### DESTROY action

DELETE http://localhost:3000/students/1.json
